const data2 = {
  devices: [
    {
      name: "LordShenron",
      device_name: "ASUS ZENFONE MAX PRO M1",
      alternate_name: "X00T",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "CakesTwix",
      device_name: "LEECO LE 2",
      alternate_name: "s2",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "CakesTwix",
      device_name: "LENOVO Z5S",
      alternate_name: "jd2019",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Abdibekov Dauren",
      device_name: "MEIZU 16TH",
      alternate_name: "m1882",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Abdibekov Dauren",
      device_name: "MEIZU 16TH PLUS",
      alternate_name: "m1892",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "ARMSM",
      device_name: "MOTO G5S PLUS",
      alternate_name: "sanders",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "AQUARIUSJR10",
      device_name: "ONEPLUS 3 AND 3T ",
      alternate_name: "oneplus3",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Eduardo",
      device_name: "ONEPLUS 6",
      alternate_name: "enchilada",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "JAISHNAVPRASAD",
      device_name: "REALME 1",
      alternate_name: "CPH1859",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Tanmay",
      device_name: "REALME 6",
      alternate_name: "RMX2001",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Chatur",
      device_name: "SAMSUNG GALAXY A10",
      alternate_name: "a10",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Chatur",
      device_name: "SAMSUNG GALAXY A20",
      alternate_name: "a20",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Gabriel",
      device_name: "SAMSUNG GALAXY J4+",
      alternate_name: "j4primelte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY M20",
      alternate_name: "m20lte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },

    {
      name: "Gabriel",
      device_name: "XIAOMI REDMI K20",
      alternate_name: "davinci",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Roger W.",
      device_name: "XIAOMI MI A1",
      alternate_name: "tissot",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "MarkDarknessK",
      device_name: "XIAOMI MI A2",
      alternate_name: "jasmine_sprout",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Marcos Almeida",
      device_name: "XIAOMI MI 6X",
      alternate_name: "wayne",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Alexander",
      device_name: "XIAOMI MI NOTE 10",
      alternate_name: "tucana",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Prajwal & Nitish",
      device_name: "Xiaomi MI 10I 5G | 10T LITE",
      alternate_name: "gauguin",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Shivam",
      device_name: "XIAOMI POCO X2",
      alternate_name: "phoenix",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Agus & ArmSM",
      device_name: "XIAOMI POCO X3",
      alternate_name: "surya",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Shriiyansh210",
      device_name: "XIAOMI REDMI 5",
      alternate_name: "rosy",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Alex",
      device_name: "XIAOMI REDMI 6 PRO",
      alternate_name: "sakura",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Sipun Ku Mahanta",
      device_name: "XIAOMI REDMI NOTE 5 PRO",
      alternate_name: "whyred",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },

    {
      name: "Spicydoughnut",
      device_name: "XIAOMI REDMI NOTE 7 PRO",
      alternate_name: "violet",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Fernando Sánchez",
      device_name: "XIAOMI REDMI NOTE 8",
      alternate_name: "ginkgo",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },

    {
      name: "A9ito",
      device_name: "XIAOMI REDMI NOTE 9 PRO",
      alternate_name: "miatoll",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },

    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY A30",
      alternate_name: "a30",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },

    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY A40",
      alternate_name: "a40",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY M30",
      alternate_name: "m30lte",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "Himanshu",
      device_name: "XIAOMI REDMI NOTE 8 PRO",
      alternate_name: "begonia",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
  ],
};
