const data = {
  devices: [
    {
      name: "LordShenron",
      device_name: "ASUS ZENFONE MAX PRO M1",
      alternate_name: "X00T",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Andrzej",
      device_name: "GOOGLE PIXEL",
      alternate_name: "sailfish",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Andrzej",
      device_name: "GOOGLE PIXEL XL",
      alternate_name: "marlin",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Amartya",
      device_name: "HUAWEI NEXUS 6P ",
      alternate_name: "angler",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "CakesTwix",
      device_name: "LEECO LE 2",
      alternate_name: "s2",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Abdibekov Dauren",
      device_name: "MEIZU 16TH",
      alternate_name: "m1882",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Abdibekov Dauren",
      device_name: "MEIZU 16T",
      alternate_name: "m1928",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Alex",
      device_name: "MEIZU 16X",
      alternate_name: "m1872",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Vitor",
      device_name: "MOTOROLA G7 POWER",
      alternate_name: "ocean",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Vitor",
      device_name: "MOTOROLA G7",
      alternate_name: "river",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "ARMSM",
      device_name: "MOTOROLA G5S PLUS",
      alternate_name: "sanders",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "CHARLIE-117",
      device_name: "MOTOROLA G3 TURBO",
      alternate_name: "merlin",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "AQUARIUSJR10",
      device_name: "ONEPLUS 3 AND 3T ",
      alternate_name: "oneplus3",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "MrMobTech",
      device_name: "REALME 1",
      alternate_name: "CPH1859",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY M20",
      alternate_name: "m20lte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY S8",
      alternate_name: "dreamlte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },

    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY S8 PLUS",
      alternate_name: "dream2lte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY NOTE 8",
      alternate_name: "greatlte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Roger W.",
      device_name: "XIAOMI MI 6X",
      alternate_name: "wayne",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Roger W.",
      device_name: "XIAOMI MI A2",
      alternate_name: "jasmine_sprout",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "HumanGlitch",
      device_name: "XIAOMI POCOFONE F1",
      alternate_name: "beryllium",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "SunnyRaj",
      device_name: "XIAOMI REDMI 5A",
      alternate_name: "riva",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "ThatisJigen",
      device_name: "XIAOMI REDMI NOTE 4",
      alternate_name: "mido",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
    {
      name: "Sipun Ku Mahanta",
      device_name: "XIAOMI REDMI NOTE 5 PRO",
      alternate_name: "whyred",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Prajwal & Nitish",
      device_name: "XIAOMI REDMI NOTE 7 PRO",
      alternate_name: "violet",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 2,
    },
    {
      name: "Amartya",
      device_name: "XIAOMI REDMI NOTE 8/8T",
      alternate_name: "ginkgo",
      IsDropped: "(SUPPORT DROPPED)",
      droppedMessage:
        "THE SUPPORT FOR THIS DEVICE IS DROPPED, DOWNLOAD AT YOUR OWN RISK.",
      isSupported: 0,
    },
    {
      name: "A9ito",
      device_name: "XIAOMI REDMI NOTE 9 PRO (GLOBAL ONLY)",
      alternate_name: "joyeuse",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 0,
    },
  ],
};
