const data2 = {
  devices: [
    {
      name: "LordShenron",
      device_name: "ASUS ZENFONE MAX PRO M1",
      alternate_name: "X00T",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "CakesTwix",
      device_name: "LEECO LE 2",
      alternate_name: "s2",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "ARM SM",
      device_name: "MOTO G5S PLUS",
      alternate_name: "sanders",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "AQUARIUSJR10",
      device_name: "ONEPLUS 3 AND 3T ",
      alternate_name: "oneplus3",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "JAISHNAVPRASAD",
      device_name: "REALME 1",
      alternate_name: "CPH1859",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY A30",
      alternate_name: "a30",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },

    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY A40",
      alternate_name: "a40",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY M20",
      alternate_name: "m20lte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Haridhayal",
      device_name: "SAMSUNG GALAXY M30",
      alternate_name: "m30lte",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Roger W.",
      device_name: "XIAOMI MI 6X",
      alternate_name: "wayne",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Roger W.",
      device_name: "XIAOMI MI A2",
      alternate_name: "jasmine_sprout",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Alexander",
      device_name: "XIAOMI MI NOTE 10",
      alternate_name: "tucana",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Wally & Nitish",
      device_name: "XIAOMI REDMI NOTE 7 PRO",
      alternate_name: "violet",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "Himanshu",
      device_name: "XIAOMI REDMI NOTE 8 PRO",
      alternate_name: "begonia",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
    {
      name: "A9ito",
      device_name: "XIAOMI REDMI NOTE 9 PRO (GLOBAL ONLY)",
      alternate_name: "joyeuse",
      IsDropped: "",
      droppedMessage: "",
      isSupported: 1,
    },
  ],
};
